### ISSUE TITLE
Send .php file - Error in the REGEX

### ISSUE THREAD

**Issue by Gilbertdelyon** [jonbeckett/virtualflightonlinetransmitter#3]
An error here
https://github.com/jonbeckett/virtualflightonlinetransmitter/blob/f96a3081e55c1484df63b2fb18b6c4103166561e/server/send.php#L68
error in the Regex
![image](https://github.com/jonbeckett/virtualflightonlinetransmitter/assets/91057837/940c9721-37c9-4c15-ab60-1b6cf4aef13c)

Should be replaced by
	`$notes         = preg_replace('/[^A-Za-z0-9.,\n -]/', '', strip_tags($notes));`

**Comment by jonbeckett** [comment]
Updated source.

**Comment by Gilbertdelyon** [comment]
Hi Jonanthan,
I have implemented the "server" folder in our web site and it works   like a charm, thak you for this nice work.

Only one issue with Transmitter:
- I installed "server" on first web server ([o2switch](https://www.o2switch.fr/hebergement-illimite/?gad_source=1&gclid=Cj0KCQjw2a6wBhCVARIsABPeH1s4vOWZxU_pd24MQFHMbDCUiyFZ7Z8I1D8ueitoS1vJwc7fg_bz-5QaAvHFEALw_wcB),  and data base was updated only once per 30 seconds.
- Then i moved to [IONOS](https://www.ionos.fr/?ac=OM.FR.FRo41K356241T7073a&itc=FRANJS8Y-TH53Y8-&utm_source=google&utm_medium=cpc&utm_campaign=SBT-FR-BRA-MIXX---IONOS---&utm_term=ionos&matchtype=e&utm_content=IONOS&gad_source=1&gclid=Cj0KCQjw2a6wBhCVARIsABPeH1tZQcptlwt0nZsJZeFi_Xv9FYmYetbOJBnj1CDO_JEPwJtg6Ll2gUMaAqnVEALw_wcB&gclsrc=aw.ds). and database was ipdated each 1 or 2 seconds. It works!

So the question is: **What is the "normal" request frequency from Transmitter**? I know a bit about php and js but unfortunatelly nothing in othe languages)

**Comment by jonbeckett** [comment]
The Transmitter client application sends an update every second. It does it
by calling "send.php"

I've had a few requests from people to implement the timer as a
configurable parameter - but people will of course set it to 1 second (just
like they used to set LittleNavMap to 1 second, which is why I eventually
had to kill the server)

**Comment by Gilbertdelyon** [comment]
> but people will of course set it to 1 second (just
> like they used to set LittleNavMap to 1 second, which is why I eventually
> had to kill the server)

AhAh! So, this confirms what had in mind!!
On our site (hosted in a low cost shared server) we have implemented a few  improvements to prevent such issue:
- cannot run the functionnality without codepin
- an easy way to change the code-pin without editing `config.php` + a 170bits codepin generator
- a stop and start functionnality. The site owner only has to click a button to stop the fonctionnality.

**Comment by jonbeckett** [comment]
The problem though - is if an instance of LNM is calling every 1 second,
those hits still get to the webserver no matter what you do.
Without throttling up-stream of the webserver, which low cost hosting won't
have - the host will see it as a DDOS attack when lots of people start
doing it :)

**Comment by Gilbertdelyon** [comment]
The site is, up to now, a small community site, so we hope all members to stay on the reasonable side. Wait and see!
I also have in mind to use the codepin to connect to whazzup_ivao.php. It's easy to add it as a parametrer in the url and to test it in whazzup. This could also limit the number of requests, specially if we change the code pin frequently.

**Comment by jonbeckett** [comment]
It won't stop the requests. It will just stop them working. That's an
important distinction.

To try to explain what I'm talking about - I have had to put
VirtualFlight.Online domain name through CloudFlare, and BLOCK all of the
transmitter URLs - because they are still getting hit hundreds of thousand
of times a day by people who still either run Transmitter, or LittleNavMap,
and still have them connected to it...

**Comment by Gilbertdelyon** [comment]
>  It won't stop the requests. It will just stop them working. That's an
> important distinction.

> which is why I eventually had to kill the server

Thank you for highlighting these point. Now I understand better what happened.

Our "server" is nested in a subfolder of our main site. 
This was the easiest way, but now I worry if we should move it to a subdomain, so that, if we become victims of our succes as you were, we will not have to kill the main domain but only the subdomain.

**Comment by jonbeckett** [comment]
You can always re-route the DNS through cloudflare - they have wonderful
controls up-stream of the request hitting the webserver :)  You don't have
to do it now - but it's a free option for the future :)

If you're going to put it in a subdomain, better to do it now :)

**Comment by Gilbertdelyon** [comment]
Thank you for your preciuos advice.

I am now improving who.php and who.js.
- Map reframing, only on the aicrafts icons instead of entire world
- new svg icon (same as in LittleNavMap)
- Callsign near to the icon (same as in LittleNAvMap)
- Full screen map button (thanks to Leaflet Fullscreen plugin)
- And, cherry on the cake, aircrafts location updating each 15 seconds by way of "setIntevall".
So that Who will be a kind of simplified Little NavMap.
I will let you know when complete

**Comment by jonbeckett** [comment]
I've tried a lot of that code over time :)  I ended up going back to basics
when I released it to the world.

I started creating a proper radar client, with trails behind the aircraft
too :)

**Comment by jonbeckett** [comment]
Here's the source - line 94 has the location of the JSON.
[radar.zip](https://github.com/jonbeckett/virtualflightonlinetransmitter/files/14850740/radar.zip)
